version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0-browsers
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Setup Environment Variables
                  command: |
                    echo "export LHCI_BASE_URL=https://www.searspartsdirect.com" >> $BASH_ENV
                    source $BASH_ENV
                    echo $LHCI_BASE_URL
            - run:
                  name: Check Environment Variables
                  command: |
                    echo $LHCI_BASE_URL
            - run:
                  name: Lighthouse cli
                  command: sudo npm install -g @lhci/cli@0.3.x
            - run:
                  name: lhci autorun
                  command: lhci collect --url=$LHCI_BASE_URL --upload.target=temporary-public-storage
            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --project my-first-firebase-projec-6baf8 --token "$FIREBASE_TOKEN" --only hosting