ci:
  collect:
    settings:
      configPath: "config/lighthouse/lhconfig.js"
    numberOfRuns: 1
    url:
    - https://www.searspartsdirect.com/brands/
    - https://www.searspartsdirect.com/categories/
