---
ci:
  assert:
    preset: lighthouse:recommended
    assertions:
      categories:performance:
      - warn
      - aggregationMethod: optimistic
        minScore: 0.25
      categories:accessibility:
      - warn
      - aggregationMethod: optimistic
        minScore: 0.6
      categories:seo:
      - warn
      - aggregationMethod: optimistic
        minScore: 0.9
  collect:
    settings:
      onlyAudits:
      - first-meaningful-paint
      - speed-index-metric
      - estimated-input-latency
      - first-interactive
      - consistently-interactive
      onlyCategories:
      - performance
      - accessibility
      - seo
    numberOfRuns: 1
    url:
    - https://www.searspartsdirect.com/brands/
    - https://www.searspartsdirect.com/categories/
